---
bibliography: references.bib
output:
  pdf_document: default
  word_document: default
---

# Introducción

El sistema de educación superior chileno ha sido uno de los ámbitos que más transformaciones ha experimentado en las últimas décadas. En el transcurso aproximado de treinta años, se ha producido un fuerte fenómeno de expansión en términos de acceso a este servicio, reflejado en una matrícula que prácticamente se ha sextuplicado; si en 1984 la cantidad de matriculados bordeaba los 190.000, el año 2021 esta cifra superaría el millón, alcanzando un total de 1.204.414 estudiantes matriculados a nivel de pregrado en alguna institución de educación superior [@consejo2021; @subsecre2021]. Estos avances en materia de cobertura se vieron también posibilitados con la ampliación y diversificación de las alternativas de ayuda financiera -expresada en forma de becas y créditos- que, desde mediados de la década del año 2000, favoreció la incorporación masiva de sectores bajos y medios anteriormente excluidos de este nivel educativo [@rama2009]. Así, para el año 2015, uno de cada tres jóvenes entre los 18 y 24 años pertenecientes al quintil de menores ingresos tenía acceso a educación superior, situación nunca antes vista en el país [@ministeriodedesarrollosocial2015].

El aumento significativo de la cobertura en educación superior ha dado lugar a que, a partir de la primera década del presente siglo, el foco de atención de instituciones, políticos y académicos se haya orientado más sistemáticamente hacia la retención de estudiantes, la que, en conjunto con los logros de aprendizaje y la titulación oportuna, pasarían a constituir aspectos clave para evaluar la eficiencia y la calidad en educación [@blanco2018; @donoso2010]. A mediados de la década del 2000, apenas un 13% de la población chilena entre 25 y 64 años había finalizado sus estudios superiores, lo que se traduce en que, para entonces, solo uno de cada diez chilenos había completado alguna carrera de educación superior [@oecd2005; @worldbank2005]. En los últimos años, sin embargo, la tasa de retención de estudiantes ha experimentado un alza significativa desde la cohorte del año 2011 (68,5%) hasta la cohorte 2018 (75%), viéndose únicamente interrumpido por el efecto conjunto de la revuelta social de octubre de 2019 y el inicio de la pandemia por COVID-19, situación que fue en parte revertida para la cohorte 2020 [@serviciodeeducaciónsuperiorsies2021].

La deserción, entendida como una situación de abandono prematuro de los estudios en donde se descarta la posibilidad de reincorporación [@himmel2002], debe comprenderse como un fenómeno de naturaleza compleja y multicausal, cuya multiplicidad de factores implicados ha obligado a la literatura especializada a proveer diferentes enfoques y perspectivas en su abordaje. A nivel general, es posible distinguir, primero, dos grandes focos en función de la decisión que tome el estudiante en el curso de su trayectoria académica: la decisión de abandonar sus estudios, es decir, de desertar; y como contraparte, la decisión de permanecer en la institución de educación superior, lo que ha sido conceptualizado bajo los títulos de permanencia, persistencia y retención [@améstica-rivas2021]. A partir de los estudios orientados a explorar la deserción, se han establecido cinco tipos de variables explicativas principales de gran relevancia hasta la actualidad: los factores individuales, académicos, económicos, institucionales y culturales [@améstica-rivas2021; @donoso2007; @estebangarcía2016]. Asimismo, diferentes autores también han sofisticado sus definiciones para establecer una distinción entre el abandono voluntario e involuntario, permanente y transitorio, así como también si la deserción es respecto de la carrera o de la institución [@elias-andreu2008; @himmel2002; @stratton2008]. Las perspectivas centradas en la retención y la persistencia, por su parte, encuentran su origen en un cambio de paradigma impulsado por la literatura europea y estadounidense, que se propuso el reemplazo de la noción de deserción como forma de evitar la comprensión del fenómeno únicamente en términos de responsabilidades individuales; la utilización del binomio "retención-persistencia" despojaría al proceso de su connotación negativa y facilitaría el reconocimiento de una doble responsabilidad, tanto de parte de la institución -asociada a la idea de *retención*- como del estudiante -vinculado a la *persistencia*- [@fernándezdemorgado2012].

Pese a estos esfuerzos por resignificar las trayectorias de abandono, que contemplan desde reconocer la cuota de responsabilidad institucional en la decisión del estudiante, así como también la inclusión del reingreso como factor que elevaría las tasas de titulación a más largo plazo [@blanco2018], la deserción puede seguir entendiéndose como una problemática de consecuencias sociales negativas más allá de que no necesariamente constituya un fracaso académico en términos individuales. El ingreso masivo a la educación superior, en particular de aquellos estratos de "primera generación", favoreció la gestación de fuertes expectativas de movilidad social por parte de estos sectores, que depositaron en la consecución exitosa de sus estudios superiores sus esperanzas de desarrollo y autorrealización [@pnud2017] . Y esto no puede incumbir de manera exclusiva al estudiante, porque si bien con la entrada a una carrera e institución de educación superior se pone en juego una dimensión emocional individual, a partir del estado del equilibrio entre las aspiraciones personales y los logros académicos alcanzados, tanto el proceso como sus resultados involucran íntimamente también a las familias, y no solo en virtud de sus propias expectativas colectivas, sino también tomando en consideración los compromisos económicos que deben asumirse en un contexto de mercantilización de la educación [@gonzález2005; @verger2013]. De esta manera, el tener en cuenta la elevada proporción que suele ocupar la inversión educativa en las economías familiares, sumado a las consecuencias económicas que supone para las instituciones -en particular para aquellas financiadas por el Estado, cuyos menores niveles de retención son con mayor razón objeto de preocupación de la política pública [@king-domínguez2020; @latercera2016]- y para el Estado [@améstica-rivas2021], obliga a entender la deserción como un evento que trasciende a la persona y que compete a la sociedad en su conjunto.

De lo anterior se desprende la necesidad tanto social como disciplinar de estudiar el comportamiento de las trayectorias académicas a través del tiempo, y de identificar los factores más relevantes que permitan predecir y frenar la ocurrencia del fenómeno. Desde la mirada de los estudios en educación, por ejemplo, los análisis de deserción y retención, particularmente desde su arista institucional, permiten evaluar dimensiones relacionadas con la eficiencia técnica de los procesos formativos en educación superior, como el diseño curricular y el desempeño de docentes [@donoso2010]. Para la sociología, es sabido que la educación actúa como uno de los principales determinantes de la posición ocupada por individuos y grupos sociales en el mercado de trabajo, así como también de las remuneraciones futuras y el prestigio asociado a los empleos [@pnud2017]. En este sentido, las trayectorias de abandono adquieren una relevancia crucial en tanto posibilita la observación de mecanismos de reproducción de desigualdades de origen en espacios que se dicen meritocráticos; el hecho de que aquellos estudiantes pertenecientes a los dos primeros quintiles de ingresos sean más significativamente propensos a desertar en su tránsito por una carrera de educación superior [@oecd2009] pone de manifiesto la inequidad a nivel de oportunidades que persiste en este nivel educativo, y donde los procesos de deserción y extensión del ciclo formativo postergan el ingreso al mundo laboral, agudizando la situación de precariedad económica de sectores vulnerables al mismo tiempo que compromete sus expectativas individuales y familiares [@donoso2010].

Es en dicho escenario que cabe preguntarse por el rol que han desempeñado los beneficios económicos otorgados por el Estado no solo en términos de las oportunidades de acceso que abre a los estudiantes beneficiados, sino también en su continuidad al interior del sistema. Para responder a esta interrogante, la presente investigación se propone una pregunta que si bien pone el acento en la arista socioeconómica del fenómeno, buscando ahondar en la influencia de ayudas financieras como becas, créditos y gratuidad en la decisión de abandonar los estudios superiores, no desconoce la complejidad y multicausalidad que reviste a la deserción como fenómeno a explicar, de modo que incorporará de igual manera otras dimensiones relevantes identificadas en la literatura. Se propone un análisis de carácter longitudinal que comprende la observación de una cohorte de ingreso a primer año por un período de cuatro años, a fin de poder estudiar el comportamiento de sus trayectorias en el tiempo y de estimar el efecto de contar con alguna ayuda económica -siendo particularmente interesante conocer el efecto de la gratuidad, dada su reciente entrada en vigencia y consecuente menor presencia en la literatura especializada como factor explicativo-, en la probabilidad de ocurrencia del fenómeno durante los dos primeros años al interior del sistema.

El presente documento se organiza, desde aquí en adelante, en cuatro grandes secciones. Primero, se presentarán antecedentes tanto del fenómeno de la deserción, por medio de la revisión de literatura teórica y empírica a nivel internacional y nacional, como del sistema de educación superior chileno y sus características. En la segunda sección se presentarán la pregunta que guiará el trabajo investigativo, los objetivos propuestos y las hipótesis planteadas en vista de los antecedentes recopilados. En tercer lugar, se expondrá el marco metodológico en el que se inscribe esta investigación, señalando cuáles fueron los datos con los que se trabajó, cómo se realizó la operacionalización de las variables y los métodos con los que se analizó la información. Finalmente, se expondrán los resultados de los análisis descriptivos y predictivos en relación con la variable dependiente.

