---
bibliography: references.bib
---

```{r echo=FALSE}
knitr::opts_chunk$set(out.width="80%", fig.pos = "!ht", out.extra = "")
```

# Antecedentes

## Revisión de la literatura teórica y empírica

### Delimitación del concepto de trayectoria

Tal como se mencionó en los párrafos introductorios, la literatura tanto teórica como empírica se ha posicionado tradicionalmente desde una perspectiva binaria en su abordaje de la experiencia de estudiantes en la educación superior, entendiéndola en función de la oposición entre el éxito (persistencia) y el fracaso (deserción) académico. Esta orientación encontraría su fundamento en la también mencionada importancia del factor retención en la evaluación de la calidad de la educación, siendo la deserción un problema relevante a nivel de gestión institucional y de políticas públicas. Pese a ello, la expansión de la educación superior en una gran cantidad de países durante los últimos años, incluyendo la mayor diversidad y heterogeneidad en la composición poblacional que le han venido aparejadas, han despertado un creciente interés académico por impulsar estudios de corte longitudinal sobre trayectorias educativas. Asimismo, el desarrollo de estas investigaciones se ha visto posibilitado por la cada vez mayor disponibilidad de datos longitudinales a gran escala, que en el caso de Chile contempla, por ejemplo, la información almacenada en repositorios estadísticos de diversas instituciones gubernamentales. En términos de los resultados obtenidos, la complejización de los análisis permitiría, por ejemplo, la identificación de factores que llevarían a estudiantes a optar por una u otra decisión -a saber, a continuar o abandonar sus estudios superiores-, así como también posibilitaría una mejor comprensión del retraso en la finalización de los programas de estudio [@haas2020].

En relación con las propuestas teóricas que se han elaborado sobre el tema, han sido varios los términos empleados por distintos autores -provenientes principalmente de países angloparlantes- para describir la experiencia que viven estudiantes durante su tránsito por la educación superior. Algunos conceptos como "trayectoria" (*trajectory*), "ruta" (*pathway*, *route*) o "recorrido" (*path*)[^1] se han utilizado indistintamente sin establecer mayores distinciones analíticas, quedando el uso de uno u otro concepto sujeto al enfoque desde el cual cada investigación se ha hecho cargo del fenómeno. Entre los esfuerzos por precisar cada término se encuentra el trabajo teórico de @pallas2003 que, a rasgos muy generales, define a las "rutas" (*pathways*) como un atributo del sistema social, en tanto constituirían secuencias de transiciones moldeadas por fuerzas tanto culturales como estructurales; mientras que las trayectorias, si bien también se erigirían como secuencias de transiciones, serían más bien un atributo perteneciente al individuo, y describirían experiencias resultantes de circunstancias y decisiones individuales. En esa misma línea, @haas2020 recogen estas definiciones y las aterrizan al contexto de la educación superior, señalando que la idea de ruta o *pathway* haría alusión a patrones de progresión institucionalmente ideales, es decir, aplicaría en aquellos casos de transición directa desde la enseñanza secundaria a la superior, y donde esta última se extienda por un período ideal de 3 o 4 años -entendiendo, por supuesto, que esta duración varía en función de programas e instituciones-. El término trayectoria, por su parte, referiría, según estos autores, a las experiencias empíricas reales e incluiría todas las transiciones y estados de matrícula comprendidos durante un período de tiempo determinado [@haas2020].

[^1]: Cabe mencionar que estas palabras han sido traducidas de manera arbitraria por la autora de este documento, considerando la escasa literatura escrita en español sobre este tema.

### Perspectivas teóricas principales en el estudio sobre trayectorias educativas

Estas indeterminaciones en términos conceptuales, sin embargo, no han impedido el florecimiento de una multiplicidad de investigaciones que, en mayor o menor medida, han encontrado asidero en los marcos teóricos existentes. @haas2020 evidenciaron, tras una extensiva revisión de la literatura cuantitativa referente al tema, que aquellos trabajos que ahondaron en los motivos detrás de distintas decisiones que los estudiantes tomaban durante su paso por la educación superior contaban con una mayor robustez teórica; mientras que aquellos que se ocuparon principalmente de describir dichas trayectorias carecían de una base teórica rigurosa, respaldándose mayoritariamente en el contenido empírico de sus resultados. Asimismo, estos autores establecieron una categorización de estos estudios en función de los distintos niveles que configuran las experiencias de los estudiantes en la educación superior, a saber, los niveles micro, meso y macro.

El nivel micro está principalmente orientado a la dimensión decisional de la experiencia educativa, y se encuentra dominado por aproximaciones teóricas que, básicamente, entienden las trayectorias como el resultado de decisiones o de series de decisiones. Así, son comunes en este campo las perspectivas centradas en el balance de costos y beneficios, que llevaría a los estudiantes -percibidos como individuos racionales- a, por ejemplo, actualizar constantemente la información con la que cuentan y a realizar inversiones en educación superior en miras de beneficios futuros [@andrews2014; @johnson2012]. En esa misma línea, análisis como el de @breen2001 ponen en relieve tanto el género como el origen social de los estudiantes en la explicación de las diferencias decisionales, argumentando que existirían desigualdades -de recursos, de acceso a información, entre otros- que actuarían como constrictores en la toma racional de decisiones de individuos y familias. Otra perspectiva ampliamente utilizada, esta vez en el nivel meso y específicamente en los estudios sobre deserción, se relaciona con el análisis de la integración de los estudiantes en los climas sociales y académicos de las instituciones de educación superior. En este caso, las llamadas "variables contextuales" (*background variables*) moldearían los objetivos y niveles de compromiso iniciales que, posteriormente, resultarían en determinados resultados académicos y determinadas relaciones interpersonales [@tinto1975]. Finalmente, los trabajos enfocados en el nivel macro, apoyándose en la premisa de que las decisiones tomadas por los estudiantes en el transcurso de su paso por la enseñanza postsecundaria se encuentran sujetas a su contexto, han indagado tanto en los contextos organizacionales de cada institución como en la estructura del sistema de educación a nivel de cada país. De esta manera, factores como las oportunidades de reingreso, la apertura del sistema en general o los mecanismos de ayuda financiera que éste provee adquieren importancia no solo en el análisis de trayectorias educativas, sino también a nivel más general en los estudios sobre cursos de vida (*life course*) [@milesi2010].

Cabe destacar, sin embargo, que la presente investigación se ha propuesto indagar en los factores que permiten determinar y predecir una decisión concreta en el transcurso de la experiencia educativa, a saber, la decisión de abandonar permanentemente el sistema. En este sentido, si bien resulta de utilidad saber cómo se han estudiado las trayectorias o *pathways* en un sentido más amplio y qué variables moldean dichas experiencias, es conveniente ahondar aun más en la decisión de desertar en sí misma, a fin de conocer tanto el comportamiento de este fenómeno en particular como los factores se han identificado como principales en su explicación.

\newpage

### El problema de la deserción en el debate internacional

La literatura internacional que aborda la deserción en la educación superior se remonta a los años 70s y 80s, período en que los esfuerzos teóricos -centrados en la noción de integración, en el nivel meso de la experiencia educativa [@haas2020]- se concentraron principalmente en corregir ciertos errores que se estaban presentando en el campo teórico y empírico respecto de la relación entre el abandono de los estudios superiores y aspectos como los antecedentes familiares y/o el rendimiento académico. @spady1970, por ejemplo, identifica una falta de claridad conceptual y de rigor metodológico en la investigación sobre el tema, en la que, además, no se considera de manera más explícita la correspondencia entre deserción y entorno institucional en que se desenvuelven los estudiantes -poniendo especial énfasis en las políticas y los estándares de calificaciones de la institución-, elemento que para el autor resultaría clave como factor explicativo del fenómeno. Siguiendo la línea de esto último, Spady también denuncia la ausencia de una categoría que agrupe estudios de enfoque analítico-explicativo frente a la predominancia de aquellos de orientación filosófica-teórica, descriptiva y predictiva, que adolecerían de una indistinción entre tipos de deserción en función de las causas que se le atribuyen. Esta indistinción es reprobada de igual manera por @tinto1975, uno de los investigadores que más ha contribuido en la producción de conocimiento sobre este fenómeno y cuya teoría goza de un estatus prácticamente paradigmático en el campo, ubicándose en el espectro de teorías que abordan la deserción desde una perspectiva organizacional e interaccionista [@braxton1997]. De acuerdo con Tinto, habría existido una tendencia por parte de la investigación a englobar, bajo el mismo rótulo de deserción, distintos tipos de abandono que comportan características muy diferentes; el no haber establecido una separación analítica adecuada entre, por ejemplo, la deserción motivada por el fracaso académico y aquella de carácter voluntario, o entre la deserción permanente y la temporal, habría dado lugar a la producción de resultados contradictorios en la investigación y, en muchos casos, a una sobreestimación de la tasa de deserción en la educación superior.

Es en base a estas consideraciones que @tinto1975 entrega una definición formal del concepto de deserción, entendiéndola, en palabras de @canales2007, como "el proceso de abandono voluntario o forzoso de la carrera en que se matricula un estudiante, por la influencia positiva o negativa de circunstancias internas o externas al alumno" (p. 175). Al igual que @spady1970, el modelo teórico propuesto por este autor pone el acento en buscar explicar el fenómeno más que ofrecer una mera descripción, con especial énfasis en la dimensión institucional que rodea a los estudiantes. Así, para Tinto resulta fundamental comprender la experiencia en la educación superior como un proceso longitudinal de interacciones entre el individuo y los sistemas académicos y sociales de la institución de la que es miembro, y en la que la continua modificación de sus objetivos y nivel de compromiso con ellos determina trayectorias de permanencia o de deserción, entendiendo ésta última como un fenómeno que puede asumir formas muy variadas. Este esquema se erigiría, además, sobre otro elemento acogido a partir de la lectura de Spady, a saber, la teoría durkheimiana sobre el suicidio y sus planteamientos sobre la noción de integración. Entender el entorno educacional como un sistema social permite ubicar la deserción como un fenómeno análogo al del suicidio en las sociedades modernas, es decir, como un evento que responde a una insuficiencia tanto en el plano de las relaciones interpersonales como en la congruencia con los patrones de la institución de educación superior en tanto colectividad, y que se relaciona con niveles de integración variables con los sistemas social y académico de dicho entorno. Ahora bien, la novedad que introduce Tinto a esta analogía formulada por Spady es la inclusión de nociones económicas al modelo, específicamente de la teoría del intercambio que propone @nye1977, que se alza sobre el principio fundamental de que los seres humanos evitan comportamientos que implican costos para decantarse por relaciones, interacciones y estados emocionales que les ofrecen algún tipo de recompensa. El entrecruzamiento de esta hipótesis y el análisis de decisiones educacionales da lugar a la comprensión de la deserción como un problema de costo-beneficio, donde la decisión de continuar o abandonar los estudios en una determinada institución de educación superior dependerá de si los beneficios que ésta ofrece son percibidos como mayores en comparación con los costos y con otras fuentes de recompensa por parte del estudiante, así como del grado de integración normativa y estructural en los sistemas anteriormente mencionados. De esta manera, el que la decisión de persistencia se encuentre asociada a niveles de compromiso variables entre el estudiante y su experiencia en educación superior permite enmarcar el escenario de deserción como un fenómeno no necesariamente negativo, en tanto la reconfiguración del esquema de metas del joven podría incluso favorecer su autorrealización.

Si bien la propuesta de @tinto1975 resulta de gran importancia y utilidad conceptual en términos teóricos, los estudios empíricos basados en el modelo muestran algunas inconsistencias en sus resultados. El trabajo de @terenzini1980, por ejemplo, concluye que si bien las variables contextuales de los estudiantes (*background characteristics*) son relevantes en el modelo, éstas no permiten establecer diferencias estadísticamente confiables entre quienes abandonan voluntariamente los estudios superiores y quienes persisten; en lugar de eso, estas características sí tendrían influencia en su interacción con las experiencias educacionales de los estudiantes. Esto se comprobaría en trabajos posteriores [@pascarella1986; @pascarella1983], en los que además se identificarían diferencias significativas en los factores que explican la persistencia en hombres y en mujeres, siendo únicamente los primeros quienes mostraron resultados congruentes con el modelo. A pesar de esto, los estudios constatan la importancia de integrar uno de los elementos fundamentales de la propuesta de Tinto en el análisis de la deserción y la persistencia en educación superior, a saber, la integración social y académica de los estudiantes, reforzando la necesidad de revestir de complejidad sociológica y psicológica ambos fenómenos.

A la luz de estas insuficiencias en el esquema previamente utilizado, @bean1980 elabora su propio modelo causal, incorporando la perspectiva de @price1977 sobre la productividad y la rotación de empleados (*employee turnover*) en contextos laborales. Definiendo deserción como la cesación de la membrecía individual del estudiante en un instituto de educación superior, el autor establece una analogía entre este fenómeno y el de la rotación en organizaciones laborales, señalando que existirían determinantes organizacionales que afectarían la satisfacción y que desembocarían en procesos de abandono educacional. De acuerdo con este modelo, las variables contextuales (*background characteristics*) deben ser tomadas en consideración para comprender las interacciones entre el estudiante y el establecimiento del que es parte. Una vez dentro de la institución, el individuo interactúa con ella y con su aparato organizacional, lo que define un determinado grado de satisfacción y, con ello, un determinado nivel de compromiso con mencionada institución. De esta manera, el modelo de Bean reafirma el lugar del compromiso institucional como la principal variable que influencia la deserción tanto en hombres como en mujeres -pese a que ambos sexos abandonan los estudios postsecundarios por diferentes razones-, lo cual es consistente con los estudios previos de @spady1970 y @tinto1975 .

Posteriormente, @cabrera1992 vendrían a renovar las críticas sobre las perspectivas organizacionales y sociológicas ya revisadas, argumentando que éstas han fallado en reconocer, tanto a nivel teórico como empírico, la importancia de los factores financieros en los procesos de persistencia y deserción, y cómo estos establecen relaciones de causalidad con las características de los estudiantes y los factores de integración y de compromiso. Sin abandonar por completo los esquemas anteriores, estos autores proponen un modelo estructural que considera las variables económicas como poseedoras de un efecto directo sobre las decisiones de persistencia, en tanto interviene en las experiencias sociales e intelectuales de los miembros de una institución de educación superior. Así, por ejemplo, la integración académica de los estudiantes se ve afectada por las preocupaciones financieras y la necesidad de asegurar recursos para el financiamiento de su educación, así como también por las limitaciones de tiempo y energía disponible para dedicar a actividades académicas. A partir de la aplicación de este modelo a la labor empírica, se obtuvo que el apoyo financiero tiene un efecto total significativo sobre la permanencia mediante la facilitación de las interacciones sociales de los estudiantes con su institución, lo que deriva en una mayor integración en los universos sociales de educación superior.

### La literatura nacional sobre deserción en educación superior

En Chile, la literatura constataba, a comienzos del nuevo siglo, una escasez de estudios especializados en la deserción a nivel de educación superior, los que, además, se encontraban principalmente orientados a la estimación de la magnitud del fenómeno. Respecto a esto, la evaluación arrojaba que, alrededor de esos años, aproximadamente la mitad de los estudiantes que ingresaban a alguna institución de educación postsecundaria abandonaban sus estudios antes de la consecución de su grado académico, siendo el primer año de carrera un momento decisivo en las trayectorias educacionales y que concentra la mayor proporción dentro de esta fracción del estudiantado @himmel2002 . Pero aun considerando las dimensiones cuantitativas de este problema, no existía una rama paralela de investigaciones encauzadas hacia la determinación de los factores que explicaran este fenómeno y que, de esta manera, pudiesen ser de utilidad para la generación de estrategias y políticas encaminadas a disminuir su ocurrencia y atenuar su impacto.

Es en medio de este vacío que @himmel2002, a fin de estimular la reflexión local sobre este problema, entrega algunas precisiones conceptuales de elaboración propia a partir de una recopilación de definiciones y modelos internacionales. Por un lado, la autora entiende la deserción como "el abandono prematuro de un programa de estudios antes de alcanzar el título o grado, y considera un tiempo suficientemente largo como para descartar la posibilidad de que el estudiante se reincorpore" (p. 95). De manera similar a lo que plantea @tinto1975, Himmel enfatiza en la necesidad de distinguir entre los tipos voluntario e involuntario de deserción, siendo el primero una decisión del estudiante y, el segundo, una decisión institucional fundada en un determinado marco normativo vigente. También, Himmel establece una distinción entre lo que designa como deserción de la carrera, es decir, un abandono en relación con un programa de estudios que puede venir acompañado de una transferencia a otro programa o de un reingreso posterior; y la deserción de la institución, que puede suponer tanto el traslado a otra institución como el abandono definitivo de los estudios terciarios. Por otro lado, también se ofrece una definición de la noción de retención que, en oposición a la idea de deserción, se expresa por "la persistencia de los estudiantes en un programa de estudios universitarios hasta lograr su grado o título" (p. 94). Sin embargo, las complicaciones con esta categoría se presentan al momento de decidir si comprenderá el logro del título académico dentro de los tiempos mínimos definidos por la institución, o si no tomarán en consideración los márgenes temporales, principalmente si se tiene en cuenta que los tiempos reales que tardan los estudiantes en alcanzar estos objetivos generalmente no se condicen con los tiempos estimados. A la luz de estas dificultades, y de las arbitrariedades asumidas por distintas investigaciones en la operacionalización de este concepto, para Himmel resulta indispensable que se adopte una definición unívoca de retención, con el fin de permitir la comparabilidad entre los estudios sobre el tema.

A partir de estas primeras definiciones, han surgido algunos esfuerzos por modelar los procesos de deserción estudiantil desde la literatura nacional. @díaz2008 propone un modelo conceptual para comprender la deserción en las universidades chilenas que sitúa el grado de motivación en el centro del problema. De esta manera, las probabilidades de persistir dentro de una institución universitaria aumentan si la motivación es de tipo positivo, y disminuyen -aumentando, a su vez, la probabilidad de desertar- si ésta es negativa. En consonancia con y retomando las ideas nucleares del modelo de @tinto1975, Díaz establece un vínculo directo entre la motivación y la integración académica y social de los estudiantes, a través de lo cual es posible introducir variables preexistentes, como las características preuniversitarias, familiares e individuales; así como también variables institucionales, propias del establecimiento de educación superior del que se forma parte. La acción permanente de estos factores sobre el individuo en el transcurso de sus años de estudio configurarían un equilibrio en una constante situación de tensión, que desembocaría en trayectorias de abandono al debilitarse cualquiera de las variables que sostienen dicho estado. En los últimos años también se han desarrollado modelos explicativos para comprender los fenómenos de deserción y retención. Un ejemplo de esto es la propuesta desplegada por @ayala2018, quienes se posicionan desde la idea de retención para elaborar un modelo que integra factores familiares, académico-educativos y económicos. Mediante un análisis de trayectorias educativas, y poniendo en práctica la técnica de ecuaciones estructurales, se construyó un esquema que apunta a la relevancia de la familia y sus aportes directos e indirectos en la permanencia en la educación superior, a través de sus efectos en relación con ingresos familiares y dependencia del establecimiento de origen.

En relación con la evidencia empírica sobre deserción y retención estudiantil con la que se cuenta en el país, los resultados coinciden con la literatura internacional en lo que respecta a la multiplicidad de factores implicados y de formas de aproximación al fenómeno. @donoso2007, por ejemplo, enmarcan la discusión sobre retención universitaria en el contexto educacional chileno, subrayando particularmente el sistema de selección de las universidades públicas y el rol que éste juega en cómo se ha comprendido la retención. La ilusión meritocrática creada a partir de los mecanismos de selección encubriría la complejidad del tema en cuestión y la incidencia de las variables socioeconómicas en el esquema, dando lugar a una "privatización del fracaso" (p. 10) -expresado en trayectorias de deserción y repitencia-, donde los resultados educativos pasan a entenderse como una consecuencia individual del estudiante y no como un proceso a través del cual la institución debe hacerse cargo de proveer los recursos adecuados, incluyendo con esto las políticas compensatorias dadas las diferencias de nivel socioeconómico y de capital cultural de las familias. Otras investigaciones también han incorporado el efecto de los compañeros en el rendimiento, reportando algunos resultados ambivalentes; si bien el efecto par es principalmente positivo en la medida que contar con compañeros con un buen desempeño académico previo a su ingreso a la institución de educación superior aumenta las probabilidades de retención, sobre todo en Centros de Formación Técnica (CFT) e Institutos Profesionales (IP), esta probabilidad disminuye cuando se cuenta con compañeros con mejores puntajes PSU en las pruebas de Matemáticas y Lenguaje y Comunicación [@bordón2015].

Algunos enfoques también se han abocado a caracterizar y determinar los principales factores que confluyen en el fenómeno desde la aplicación de metodologías cualitativas. A nivel general, los resultados señalan a los estudiantes vulnerables como quienes se encuentran en una mayor situación de riesgo, existiendo dificultades académicas, emocionales/afectivas, sociales y económicas que propician un peor desempeño y reducen las probabilidades de que el estudiante permanezca en la institución [@canales2009]. Éstos diseñarían distintas estrategias para sobrellevar los problemas de integración, como la estimulación de una fuerte orientación al logro, el esfuerzo y la perseverancia, el autoconocimiento y el establecimiento de redes sociales de apoyo entre pares, elemento que resulta crucial durante el transcurso del primer año de estudios. Es pertinente mencionar, sin embargo, que los factores específicos que provocan la deserción difieren dependiendo de si ésta es de tipo temporal o permanente [@canales2007]. Si bien las razones no académicas juegan un rol fundamental para ambas categorías, la deserción temporal se ve más fuertemente asociada a causas vocacionales, motivacionales y socioculturales, mientras que la deserción permanente encuentra su origen en condicionantes socioeconómicos y familiares. En este sentido, gran parte de los estudiantes desertores declararon no haber contado con ayuda institucional y financiera que permitiera atenuar los costos económicos de emprender una carrera de educación superior.

### Incidencia de la ayuda financiera como variable explicativa

Lo anterior permite comprender a los mecanismos de financiamiento y apoyo económico como una de las variables de mayor incidencia en las trayectorias en educación superior, aunque esta comporte efectos desiguales dependiendo de si se trata de la educación de tipo universitaria o técnico profesional [@blanco2013; @hernández2007]. En Chile, los y las jóvenes deben tomar en consideración sus realidades económicas, con las restricciones y libertades que pueden permitirse, desde el momento en que deciden continuar sus estudios en algún instituto de educación superior, siendo sensibles a las variaciones de ingresos tanto cuando lo que se escoge son carreras profesionales como cuando la decisión gira en torno a no proseguir la enseñanza postsecundaria. No obstante, esto no ocurre cuando la carrera de elección pertenece al sector técnico; éstas suelen ocupar una posición secundaria dentro de la jerarquía de alternativas y, por tanto, quienes las eligen suelen contar con restricciones para pagar una carrera profesional o se ven excluidos de ellas a causa de su rendimiento académico. La educación técnica también se ve perjudicada por la ayuda financiera a nivel de matrícula; no solo ésta tiene un impacto menor que en carreras universitarias, sino que también se produce un "efecto de sustitución" [@blanco2013, p.115] en donde ser beneficiario para una institución universitaria disminuye la probabilidad de matricularse en una carrera técnica.

Pese a esto, la literatura confluye en declarar que las ayudas financieras provocan un efecto positivo significativo en la reducción de las tasas de deserción [@alarcón2018; @barrios2011; @flores2020; @fuentes2019; @santelices2016]. De manera transversal, que un estudiante sea beneficiario de algún tipo de beca y préstamo estatal, institucional y/o privado implica que tendrá más probabilidades de permanecer en la educación superior. Ahora bien, la efectividad de estos beneficios varía en función del tipo de estudiante y del tipo de ayuda recibida. Por ejemplo, se ha encontrado la existencia de una relación inversa entre el impacto de las ayudas y los ingresos del estudiante, de modo que el impacto se acrecienta cuanto menores sean los ingresos percibidos por el hogar del beneficiario y viceversa. Por otra parte, las ayudas de mantención se relacionan más fuertemente con la persistencia que las de arancel, probablemente debido a que, al continuar sus estudios, los estudiantes dejan de aportar ingresos al hogar y buscan no ser un gasto adicional para la economía familiar. Otro resultado de importancia refiere a la solidez de la correlación entre la asignación de créditos y la persistencia, siendo los beneficiarios del Crédito con Aval del Estado (CAE) dos veces más propensos a permanecer en la institución que aquellos que reciben el crédito Fondo Solidario. También, la diferencia de retención de estudiantes beneficiarios del CAE corresponde a aproximadamente 3 puntos porcentuales por sobre aquellos que acceden al beneficio de la Gratuidad, demostrando que ésta última política no parece mejorar demasiado la situación de deserción universitaria en comparación con el CAE.

Teniendo en cuenta estos resultados, es también de importancia mencionar que los estudios que ahondan en el rol que los beneficios socioeconómicos suponen no solo en la decisión de desertar, sino que, más generalmente, en las decisiones que los estudiantes toman desde su ingreso al sistema de educación superior, han identificado un importante problema de endogeneidad en el análisis [@bettinger2015; @meneses2010]. En otras palabras, la asignación de las ayudas financieras -sobre todo si es realizada por parte del Estado- suele estar enfocada únicamente en ciertos grupos, lo que en términos estadísticos implica vincular otras características asociadas a dichos grupos a la misma variable que se quiere explicar. De este modo, los intentos por evaluar el impacto de este tipo de beneficios en las decisiones de los estudiantes ha empujado a investigadores a innovar en el desarrollo de sus estimaciones, por medio diseños de regresiones discontinuas [@kane; @vanderklaauw2002] o a través del "*propensity-score matching*" [@agodini2004; @santelices2013], por nombrar algunos ejemplos.

### Otras aproximaciones y reconceptualización del fenómeno

Dadas sus múltiples repercusiones, la deserción en el sistema de educación superior chileno ha sido también objeto de preocupación por parte de otras disciplinas, principalmente desde el campo de la ingeniería, por medio de la aplicación de técnicas e instrumentos que permiten explicar y predecir su ocurrencia; y desde la economía, que se ha ocupado de evaluar los costos que ésta presenta tanto para los estudiantes y sus familias, como para las instituciones y el Estado [@améstica-rivas2021; @castrolópez2020; @larroucaudemagalhaes-calvet2013; @ramírez2018]. Dentro de los resultados obtenidos, se ha corroborado la multicausalidad del fenómeno, aludiendo a la intervención de factores individuales, socioeconómicos, demográficos e institucionales, incluyendo las variables de financiamiento en la ecuación. Las variables identificadas como de mayor relevancia han sido incorporadas en distintos modelos predictores de la deserción futura. Algunas investigaciones que han aplicado modelos de Machine Learning encuentran que los atributos sociodemográficos son los más relevantes en la explicación de la deserción temprana y el promedio de enseñanza media el más importante para el egreso oportuno; otras, que utilizan técnicas de minería de datos como la Clasificación Basada en Árboles de Decisión (CBAD) señalan como relevantes a factores como el promedio de notas, los años de avance en la carrera y los puntajes obtenidos en las pruebas de selección. Por último, desde la economía se han empleado métodos de análisis de eventos para describir y estimar los costos implicados en la forma de financiamiento de la carrera de estudiantes desertores. Desde el punto de vista del costo de la deserción, el monto en cuatro años bordea la cifra de los USD 23 millones; desde la perspectiva del financiamiento, se ha obtenido que la beca de gratuidad es el factor más importante del costo de deserción (43,3%).

Finalmente, y en una perspectiva diferente, investigaciones más recientes han buscado reconceptualizar la deserción para dejar de entenderla necesariamente como un fracaso académico, centrándose en aquella porción de estudiantes que, tras haber abandonado sus estudios durante el primer año, opta por el reingreso [@blanco2018]. El análisis longitudinal de las trayectorias educacionales permite concluir que alrededor de la mitad de los estudiantes que se retira de su programa se reincorpora hacia el tercer año [@rolando2012] o se cambia de área de estudios, lo cual pone de relieve los factores vocacionales y de orientación en el esquema de deserción y reingreso. @blanco2018 también identifican resultados diferenciados dependiendo del tipo de institución. De este modo, para estudiantes del sector técnico profesional (CFTs e IPs), las probabilidades de deserción muestran una asociación con las condiciones académicas y socioeconómicas, y el reingreso presenta indicadores más altos para aquellos que lo hacen al sector universitario en comparación con quienes se mantienen en su posición original; mientras, las cifras de deserción en estudiantes universitarios son menores y sus determinantes corresponden a un perfil opuesto al del reingreso, siendo los estudiantes más vulnerables quienes se concentran en la proporción de desertores o de reingresantes a alternativas del sector técnico profesional. Con todo, se obtiene que si bien el sistema de educación superior presenta deficiencias, es flexible y efectivo en cuanto a su capacidad de captar reingresantes, lo que, a más largo plazo, permite la titulación de un porcentaje significativo de estudiantes.

## El sistema de educación superior en Chile

### Composición institucional y sociodemográfica

Como se señaló en los párrafos introductorios, en los últimos años el sistema de educación superior chileno se ha caracterizado por presentar una creciente diversidad institucional, principalmente como resultado del incremento significativo de la oferta privada y del sector no universitario. A partir de esta expansión, es posible identificar cuatro grupos de instituciones de educación superior: primero, el de las universidades estatales, que contempla 18 universidades a lo largo del país; el de las "universidades G9", que agrupa a aquellas universidades privadas creadas previo a 1981; luego, el de las universidades privadas, que engloba a todas estas instituciones fundadas con posterioridad a esa fecha; y finalmente, el grupo "CFT e IP" incluye a los Centros de Formación Técnica e Institutos Profesionales [@galleguillosc.2016].

Pero pese a que el desarrollo cuantitativo del sistema sin duda constituye un avance en la democratización de este nivel educativo, el acceso a estos cuatro tipos de instituciones se encuentra aún profundamente segmentado. Así, por ejemplo, en relación con la dependencia administrativa del establecimiento de procedencia del estudiante, se observa una marcada tendencia por parte de aquellos provenientes de establecimientos particulares pagados a optar por instituciones privadas [@galleguillosc.2016], situación que contribuiría a la conformación de universidades elitistas y altamente elitistas [@muñoz2013]. Por su parte, los estudiantes provenientes de establecimientos particulares subvencionados, pero principalmente aquellos que cursaron sus estudios secundarios en centros educativos municipales, optan preferentemente por matricularse en el sector técnico-profesional (CFTs e IPs). Este sector se caracteriza, además, por acoger tanto a estudiantes con puntajes promedio más bajos en las pruebas PSU de Matemática y Lenguaje y Comunicación, como a quienes no participan de estos procesos de selección. También, es más común que estudiantes procedentes de los cinco primeros deciles de ingreso se matriculen en CFTs e IPs, en contraposición a las universidades del G9 y privadas que suelen recibir a los deciles de mayores ingresos. De esta manera, se observa una pronunciada desventaja para las instituciones técnico-profesionales, pese a ser el sector cuya matrícula de pregrado experimentó un mayor crecimiento durante el período 2007-2016 -un 8,9% promedio anual en comparación con la matrícula universitaria, que solo se incrementó en un 2,9%- [@galleguillosc.2016].

### Mecanismos de financiamiento

Las instituciones que componen el sistema de educación superior chileno financian sus actividades por medio de tres grandes vías: a través del gasto público y los aportes que recibe por parte del Estado; los aranceles que cobran a los estudiantes y sus familias; y la venta de servicios y otros ingresos, entre los que se cuentan las donaciones, los ingresos por cursos y programas de extensión, entre otros [@galleguillosc.2016]. En relación con los aportes fiscales asignados para las universidades, se distinguen también tres modos: el Aporte Fiscal Directo (AFD), que se destina de manera exclusiva a entidades pertenecientes al Consejo de Rectores de Universidades Chilenas (CRUCH) y que se transfiere tanto en función de criterios históricos como por indicadores de desempeño; el Aporte Fiscal Indirecto (AFI), que constituye el aporte basal más significativo para las instituciones privadas y se entrega en consideración de los puntajes PSU de estudiantes de primer año; y los fondos asociados a desempeño [@galleguillosc.2016; @paredes2015]. En el caso del grupo CFTs e IPs, la contribución más relevante es el Fondo de Desarrollo Institucional (FDI), un fondo concursable que beneficia a proyectos que busquen el desarrollo de la educación superior y el mejoramiento de la calidad académica [@galleguillosc.2016].

Por otro lado, se encuentran los costos cargados a las familias a través de los aranceles, aspecto del sistema de educación superior que ha sido objeto de controversia por lo elevado de estos montos. Tal como se mencionó más arriba, la incorporación de sectores menos aventajados al sistema de educación superior se vio posibilitado en gran medida por la ampliación de las alternativas de ayuda financiera provistas por el Estado que, desde el año 2006, le permitieron a estudiantes pertenecientes a instituciones privadas, tanto universitarias como técnico-profesionales, acceder masivamente al conjunto de becas y créditos para el financiamiento de sus estudios terciarios [@paredes2015]. De este modo, como complemento a los recursos que ellos mismos deben desembolsar para el pago de los aranceles, los alumnos pueden acceder también a los beneficios estatales en forma de becas y créditos, y a la oferta de ayudas que proporcione la institución en la que se encuentra matriculado. Por otro lado, se encuentran los costos cargados a las familias a través de los aranceles, aspecto del sistema de educación superior que ha sido objeto de controversia por lo elevado de estos montos. Tal como se mencionó más arriba, la incorporación de sectores menos aventajados al sistema de educación superior se vio posibilitado en gran medida por la ampliación de las alternativas de ayuda financiera provistas por el Estado que, desde el año 2006, le permitieron a estudiantes pertenecientes a instituciones privadas, tanto universitarias como técnico-profesionales, acceder masivamente al conjunto de becas y créditos para el financiamiento de sus estudios terciarios [@paredes2015]. De este modo, como complemento a los recursos que ellos mismos deben desembolsar para el pago de los aranceles, los alumnos pueden acceder también a los beneficios estatales en forma de becas y créditos, y a la oferta de ayudas que proporcione la institución en la que se encuentra matriculado.

Como se expresó anteriormente, de manera general, las ayudas financieras que otorga el Estado pueden clasificarse entre becas y créditos. El sistema de becas se compone básicamente de las becas de arancel y de las becas complementarias de mantención. De acuerdo con la última actualización del portal de la @subsecretaríadeeducaciónsuperior, actualmente se cuenta con un total de 18 becas de arancel, las que son asignadas principalmente en función de criterios socioeconómicos y académicos -aunque existen becas especiales que se otorgan siguiendo otros criterios, como las becas vocación de profesor o las becas de reparación- [@paredes2015]. Por su parte, las becas complementarias de mantención buscan asistir a los estudiantes más vulnerables en los gastos asociados a sus estudios, aportando en áreas como alimentación, residencia, entre otros, y son entregadas a través de la Junta Nacional de Auxilio Escolar y Becas [JUNAEB] [@junaeb]. Además, el Estado otorga dos apoyos financieros en la forma de créditos para aquellos estudiantes que no cumplen con los requisitos para optar a becas de arancel, a saber, el Fondo Solidario de Crédito Universitario (FSCU), destinado a alumnos que hayan obtenido sobre 475 puntos en la Prueba de Transición a la Admisión Universitaria (PDT), se encuentren matriculados en universidades pertenecientes al CRUCH y pertenezcan al 80% de la población de menores ingresos; y el Crédito con Garantía Estatal (CAE), otorgado a estudiantes matriculados en cualquier institución de educación superior que se encuentre acreditada y adscrita al Sistema de Crédito para Estudios Superiores, y hayan obtenido un puntaje promedio igual o superior a 475 en la PDT -para el caso de las universidades- o un promedio de notas igual o superior a 5,29 -para postulantes a CFTs e IPs-. Cabe destacar que la entrega de este préstamo no cuenta con requisitos socioeconómicos [@subsecretaríadeeducaciónsuperiorb]. De lo anterior se extrae que el CAE es un crédito más masivo y flexible que el FSCU, a pesar de contar con una forma de pago en cuotas fijas y no con un monto supeditado al ingreso, como sí ocurre en el segundo [@paredes2015].

Finalmente, y como uno de los aspectos de mayor relevancia para el desarrollo de esta investigación, a contar del año 2016 entra en vigencia la Ley Corta de Gratuidad a través de la modificación de la Ley de Presupuestos, por medio de la cual no solo se asegura la educación gratuita para una porción importante de estudiantes, sino que también se apunta al mejoramiento de los estándares de calidad para todos los tipos de instituciones que componen el sistema de educación superior [@latercera2015]. En términos de cobertura, si bien esta medida contemplaba primeramente a las familias pertenecientes a los cinco deciles de menores ingresos del país, se estimaba que iría avanzando de manera progresiva hacia la universalización en el acceso. Dos años más tarde, la gratuidad se consolidaría con la promulgación de la Ley 21091, la cual descansa sobre la consagración de la educación superior como un derecho cuya provisión debe encontrarse al alcance de todas las personas [@ley210912018]. Actualmente, la política se encuentra dirigida a las familias correspondientes al 60% de menores ingresos cuyos miembros cursen sus estudios en alguna institución adscrita a este beneficio -para lo cual deben cumplir con una serie de requisitos asociados a la calidad académica y a la equidad en los procesos formativos- [@subsecretaríadeeducaciónsuperiorc]. Así, y tomando en consideración todo lo anterior, más de 795 mil estudiantes se vieron beneficiados con el otorgamiento de alguna ayuda del Estado para financiar sus estudios superiores tras el segundo período de asignación -entre gratuidad, becas y créditos-, siendo más de 430 mil aquellos que obtuvieron la asignación de la gratuidad, cantidad que ha ido al aumento respecto de años anteriores principalmente a partir de la adscripción de nuevas instituciones a esta política [@subsecretaríadeeducaciónsuperior2021].
