# Conclusiones

El planteamiento y posterior desarrollo de la presente investigación se ha visto impulsado, principalmente, por dos grandes motivaciones. En primer lugar, a consecuencia del genuino interés en el campo de la educación como espacio clave en la conformación estructural de la sociedad y, más específicamente, en la educación superior como depósito de las esperanzas y expectativas de movilidad social de miles de familias. En segundo término, y en directa relación con la motivación anterior, a partir de la pregunta por los desafíos que actualmente corresponde enfrentar en miras de alcanzar mayores estándares de equidad educativa, en un escenario donde acceder a la educación post-secundaria cada vez más se aleja más de ser el lujo de unos pocos. La combinación de ambas inquietudes llevó a poner el foco sobre el otorgamiento de ayuda financiera por parte del Estado, aspecto que, al cubrir parte de los elevados aranceles cargados sobre los hombros de los estudiantes, contribuyó enormemente a superar una de las principales brechas en materia de acceso a este nivel educativo. Habiendo superado la primera barrera, entonces, cabía preguntarse por las desigualdades que se manifestaban una vez dentro del sistema, y en qué medida tales ayudas contribuían a atravesar exitosamente la senda de los estudios superiores.

Con tales preocupaciones en mente, el análisis que aquí se propuso apuntó al estudio de la deserción, incorporando la asignación de beneficios arancelarios como un factor determinante en la probabilidad de abandonar de manera permanente el sistema de educación superior. A partir de un trabajo que involucró la reconstrucción de trayectorias a través de la unión de distintos sets de información, así como también el análisis de asociaciones entre variables y la estimación de modelos de regresión logística para el cálculo de probabilidades, se obtuvo que, tal como se planteó en la primera hipótesis de investigación, los estudiantes que fueron beneficiarios de alguna ayuda financiera efectivamente contaron con menores probabilidades de deserción; y si bien la diferencia en comparación con aquellos que no contaron con ayudas no fue demasiada, la distancia se acrecentó al controlar por otras variables socioeconómicas tales como el ingreso o el nivel educacional de la madre, llegando a ubicarse 2.29 chances por sobre las del otro grupo. Por su parte, la segunda hipótesis principal, referida al efecto diferenciado que cada tipo de ayuda económica ejercería sobre la probabilidad de desertar, solo fue parcialmente confirmada; el haber accedido a un crédito como el CAE disminuyó la probabilidad de desertar en comparación con la gratuidad, pero la magnitud de esta diferencia resultó ser menor que lo esperado. La teoría del mayor efecto disuasivo de los créditos por sobre la gratuidad se debilitó aún más al confrontar el efecto de esta última con el del FSCU, el cual incluso mostró encontrarse más asociado a la deserción que la gratuidad. A pesar de ello, se observó que el aumento del compromiso económico sí tuvo un impacto de importancia en el caso de los estudiantes beneficiados con becas arancelarias, en los cuales la probabilidad de desertar se redujo considerablemente al combinar becas y créditos en comparación con haber accedido solo a alguna beca.

La incorporación de otras variables predictoras en la estimación de modelos de regresión, agrupadas en las distintas dimensiones que la literatura especializada ha identificado como relevantes y que tradicionalmente ha utilizado en investigaciones similares, dejó tras sí, también, algunos resultados a destacar. Los gráficos dispuestos en las Figuras 6.1. y 6.2. de la sección de resultados y la distribución de coeficientes que exhiben permitieron reconocer que, en términos generales, los predictores demográficos y socioeconómicos (género, ingresos, asignación de ayuda financiera y nivel educacional) se encuentran más fuertemente relacionados con la probabilidad de deserción que las otras dos dimensiones, al menos considerando el alejamiento de cada categoría respecto de aquella empleada como referencia para cada variable. Lo anterior es congruente con lo propuesto en la tercera hipótesis de investigación, siendo todos los coeficientes, además, estadísticamente significativos. Se corroboró, también de manera parcial, la asociación negativa entre las covariables académicas y la probabilidad de abandono permanente del sistema; la correlación más fuerte se presentó al considerar el promedio de notas de enseñanza media como predictor, pero esta disminuyó e, incluso, se invirtió, cuando se trató de mediciones más indirectas del rendimiento académico individual, como el puntaje obtenido en la PSU -test estandarizado cuya preparación se realiza por medio de la repetición mecánica de ejercicios- y el puntaje ranking -que expresa la posición del estudiante en su contexto educativo-. Asimismo, se demostró que las características del entorno institucional de los estudiantes juegan también un rol en el fenómeno estudiado. Si bien la incorporación de variables relativas al establecimiento educacional donde los estudiantes finalizaron su enseñanza media puso de manifiesto que al aumentar la vulnerabilidad de los contextos educativos se incrementa la probabilidad de desertar, la distancia más significativa entre categoría y grupo de referencia se registró en la variable vinculada al tipo de institución de educación superior en que cada estudiante se matriculó, siendo las entidades ligadas al sector técnico profesional (CFTs e IPs) las que más se asocian a la probabilidad de desertar al comparar con las universidades privadas.

Considerando todo lo anterior, y en términos muy generales, se estima que los resultados alcanzados en esta investigación se inscriben dentro de los márgenes esperados a partir de la revisión de estudios similares en el campo de las trayectorias educativas y la deserción. A pesar de las cifras dispares obtenidas en los análisis que compararon entre los distintos niveles de influencia según tipo de ayuda financiera, el diagnóstico relativo a la asignación de beneficios arancelarios y sus efectos positivos en la disminución de la probabilidad de deserción se suma al gran cúmulo de investigaciones que han identificado a este factor como determinante en el éxito de las trayectorias estudiantiles en la educación superior. Además de confirmar, una vez más, la relevancia de factores socioeconómicos en la determinación de la probabilidad de desertar, el presente trabajo también corroboró que el mejor desempeño académico previo al ingreso también contribuye en reducir la probabilidad de abandonar permanentemente el sistema, aspecto que, de acuerdo con la literatura, se habría encontrado mayormente asociado al abandono de tipo transitorio. En medio de estos resultados más bien confirmatorios, se considera que uno de los aportes principales de esta investigación fue la inclusión de la gratuidad como categoría dentro de los tipos de ayuda financiera posibles, por medio de un análisis que tuvo como protagonista a la primera generación de estudiantes, de todas las instituciones de educación superior existentes, que contó con dicho beneficio. Resulta relevante destacar, también, la incorporación de estudiantes reingresantes dentro de la categoría más amplia de persistencia, decisión que fue motivada principalmente por el reconocimiento otorgado a este grupo por parte de investigaciones recientes.

Sin embargo, el desarrollo de este estudio contó, también, con limitaciones de diversa índole. Una primera limitación surgió a partir de la tensión que debió conciliar la multicausalidad del fenómeno a explicar y la necesidad de delimitación propia de una memoria de título, situación que obligó a excluir un trabajo adicional de recolección de datos primarios que hubiese permitido añadir más variables y/o dimensiones de importancia. Por ejemplo, no se pudo contar con mayor información relativa a las familias y que podría haber enriquecido los resultados de la dimensión socioeconómica, como la cantidad de personas que componen el hogar, si es que otras personas cursaban un programa de educación superior al momento del ingreso, si el estudiante es padre o madre, entre otras. La naturaleza cuantitativa del estudio también limitó las posibilidades de acceder a motivaciones menos estandarizables para abandonar los estudios, las cuales, al englobar una multiplicidad de factores de infinita diversidad, probablemente hubiesen exigido sacrificar la extensión de la muestra. Es posible identificar, también, limitaciones que le son particulares a este trabajo investigativo. En primer lugar, la intención de conocer el efecto de una política que cuenta apenas con seis años desde su entrada en vigencia repercutió en la exclusión de un mayor número de cohortes en el análisis, integración que suele hacerse en investigaciones similares y que reviste de mayor consistencia a los resultados. Por otro lado, y tomando en cuenta las limitaciones recién expuestas, el no haber establecido distinciones entre el sector universitario y el técnico profesional en los análisis aportó con generalidad a la vez que restó en especificidad; al tratarse de instituciones tan distintas unas de otras, es posible que se hayan pasado por alto resultados diferenciados según sector que habrían contribuido a un mejor conocimiento del fenómeno.  

Tanto a raíz de estas limitaciones como de los resultados obtenidos a partir de la experiencia investigativa, se estima conveniente proponer algunas ideas para investigaciones futuras. Siguiendo la línea del párrafo anterior, resultaría interesante observar las variaciones -¿o la ausencia de variación?- que pudiese experimentar la gratuidad como predictor en un análisis que distinga al sector universitario del técnico profesional, tomando en consideración las enormes diferencias presentes tanto a nivel institucional como en la composición socioeconómica y motivacional del estudiantado. Por lo demás, un estudio de tales características debería esperar que unas cuantas generaciones hayan concluido sus estudios superiores, a fin de engrosar el número de cohortes y comparar los resultados, por ejemplo, al aumentar la cantidad de instituciones adscritas a la política, o bien entre las cohortes anteriores al surgimiento de este beneficio y aquellas que sí pudieron optar a él. En cuanto a las posibles líneas de investigación que emergen de los resultados aquí presentados, específicamente al considerar los efectos de la variable PSU, es de interés conocer el comportamiento de la nueva Prueba de Acceso a la Educación Superior (PAES) como predictor de la probabilidad de deserción; en tanto se trata de una prueba que, primero, no ajusta los desempeños individuales a una distribución normal y que, además, brinda a los estudiantes la posibilidad de elegir los mejores puntajes al ofrecer dos oportunidades de rendición anuales, cabe preguntarse si su incorporación reflejaría de mejor manera del rendimiento académico previo, dando así una mayor coherencia interna entre factores académicos. Es ciertamente un elemento a seguir profundizando en futuras investigaciones, también, el caso de los estudiantes matriculados en CFTs e IPs, en relación con los patrones específicos de persistencia, reingreso y deserción y su conjugación con las distintas dimensiones que circundan al fenómeno, sobre todo considerando que se trata de un sector que ha ido creciendo en número de matrícula durante los últimos años.

Como observación final, se sostiene nuevamente que la creación de la política de gratuidad -así como todo el sistema de becas y créditos a nivel general- constituyó, sin duda, una ayuda para que grupos más desaventajados pudiesen acceder a cursar un carrera de educación superior. Pese a ello, los resultados de este estudio y de otros similares han denunciado que este beneficio sigue siendo insuficiente por sí mismo en lo que respecta a su impacto en la continuidad de sus beneficiados al interior del sistema, sobre todo al establecer una comparación con aquellas ayudas que implican el endeudamiento de los estudiantes. Tal diagnóstico es de particular interés no solo para el campo de investigación en educación y, obviamente, para quienes aspiran a cursar estudios postsecundarios, sino que lo es también para el Estado, que cada año debe destinar más recursos para la cobertura de los aranceles de quienes acceden a este beneficio. En este sentido, se estima necesario que el foco de acción se traslade a nivel de cada tipo de institución y, de forma más específica, a nivel de cada institución de educación superior. Si bien en este estudio no se incluyó el efecto de las ayudas institucionales que cada entidad provee a sus matriculados, se considera que la acción concertada entre el Estado y estas instituciones podría contribuir no solo a mermar las tasas de deserción, sino también a disminuir los tiempos de titulación y a mejorar la experiencia de estudiar en la educación superior en términos generales. 


























